# Generated by Django 4.2.3 on 2023-08-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
